---
# tasks file for ansible-prep


- name: Add user for Ansible control user
  user:
    name: "{{ansible_usr}}"
    password: "{{ansible_pwd}}"
    shell: /bin/bash
    groups: "{{sudo_grp}}"
    append: yes
    state: present
    update_password: on_create

- name: Add authorized key for Ansible user
  authorized_key:
    user: "{{ansible_usr}}"
    state: present
    key: "{{ansible_key}}"
    # key: "{{ lookup('file', 'id_rsa.pub') }}"

- name: Copy in AccountsService file to make {{ansible_usr}} a system user
  copy:
    src: AccountsService
    dest: "/var/lib/AccountsService/users/{{ansible_usr}}"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu"
