---
# tasks file for ansible-prep


- name: Add user for Ansible control user
  user:
    name: "{{ansible_usr}}"
    password: "{{ansible_pwd}}"
    shell: /bin/bash
    groups: "{{sudo_grp}}"
    append: yes
    state: present
    update_password: on_create

- name: Add authorized key for Ansible user
  authorized_key:
    user: "{{ansible_usr}}"
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"