---
# tasks file for base_httpd


- name: Add user for Ansible control (DEB)
  user:
    name: "{{ansible_usr}}"
    password: "{{ansible_pwd}}"
    shell: /bin/bash
    groups: sudo,adm
    append: yes
    state: present
    update_password: on_create
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"


- name: Add user for Ansible control (RHEL)
  user:
    name: "{{ansible_usr}}"
    password: "{{ansible_pwd}}"
    shell: /bin/bash
    groups: wheel
    append: yes
    state: present
    update_password: on_create
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"


- name: Add authorized key for Ansible user
  authorized_key:
    user: "{{ansible_usr}}"
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"