---
# tasks file for ansible-prep

- name: Gather facts from new server
  setup:
    filter: ansible_default_ipv4.address

- debug:
    msg: "Ansible User ID: '{{ ansible_user_id }}'. Ansible SUDO User: '{{ ansible_env.SUDO_USER }}'."

- name: Check if user pi exists
  getent:
  database: passwd
  key: pi
  fail_key: False
  register: user_pi

- include_tasks: pi.yml
  when: user_pi is succeeded

- include_tasks: philote.yml


