---
# tasks file for ansible-prep

- name: Gather facts
  setup:
    filter: ansible_default_ipv4.address

- name: Check if user pi exists
  getent:
    database: passwd
    key: pi
  register: user_pi
  ignore_errors: True
  when: ansible_distribution == "Debian"

- name: Lock down or Delete pi user
  include_tasks: pi.yml
  when: user_pi is succeeded and ansible_distribution == "Debian"

- name: Setup Ansible user
  include_tasks: ansible.yml