---
# tasks file for base_httpd


- name: Add user 'philote' for Ansible control (DEB)
  user:
    name: philote
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$u7WbTX3IA3U5ugjt0GW.P1
    shell: /bin/bash
    groups: sudo,adm
    append: yes
    state: present
    update_password: on_create
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"


- name: Add user 'philote' for Ansible control (RHEL)
  user:
    name: philote
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$u7WbTX3IA3U5ugjt0GW.P1
    shell: /bin/bash
    groups: wheel
    append: yes
    state: present
    update_password: on_create
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"


- name: Add authorized key for 'philote'
  authorized_key:
    user: philote
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"