---
# tasks file for base_httpd


- name: Lock down 'pi' user (if it exists and is in use) prior to deletion
  user:
    name: pi
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$u7WbTX3IA3U5ugjt0GW.P1
    shell: /dev/null
    groups: null
    append: no
    state: present
    update_password: always
  when: ansible_user_id == "pi" or ansible_env.SUDO_USER == "pi"
  register: user_lockdown


- name: User or Sudo user is not 'pi'
  block: 
  - name: kill all processes owned by user 'pi'
    action: shell pkill -u pi

  - name: Remove user 'pi' (when not in use)
    user:
        name: pi
        state: absent
        remove: yes
    register: user_lockdown
    
  when: ansible_env.SUDO_USER != "pi" or not ansible_user_id != "pi"
