---
# tasks preflight file for ansible-prep

- name: Ansible-Prep.PreFlight - Check that variables are defined and set correctly
  assert:
    that:
      - ansible_usr is defined
      - ansible_pwd is defined
      - ansible_key is defined
      - default_usr is defined
    fail_msg: "variables must be defined"
    success_msg: "variables are defined"

# Install Redhat EPEL Repo - we need this for some of our dependencies
- name: Ansible-Prep.PreFlight - Add EPEL Release
  yum:
    name: epel-release
  when:
    - ansible_os_family == "RedHat"
    - local_repos


- name: Ansible-Prep.PreFlight - Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_install }}"
  ignore_errors: True



- name: Ansible-Prep.PreFlight - Install Open VM Tools packages
  package:
    name: open-vm-tools
    state: present
  when:
    - ansible_virtualization_type == "VMware"
    - ansible_virtualization_role == "guest"