---
# tasks file for ansible-prep

- name: Install RedHat Prerequisits
  block:
    - name: Install EPEL Release repo
      yum:
        name: epel-release

    - name: Install SELinux Python Library
      yum:
        name: libselinux-python
      when: ansible_selinux_python_present == "false"
  when: ansible_os_family == "RedHat"


- name: Install packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{package_install}}"
  ignore_errors: True



- name: Install Open VM Tools packages
  package:
    name: open-vm-tools
    state: present
  when: ansible_virtualization_type == "VMware" and ansible_virtualization_role == "guest" 
