---
# tasks file for ansible-prep

# Install Redhat EPEL Repo - we need this for some of our dependencies
- name: Repo Management - Install EPEL Release
  yum:
    name: epel-release
  when: ansible_os_family == "RedHat"


- name: Package Manager - Install packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{package_install}}"
  ignore_errors: True



- name: VMWare - Install Open VM Tools packages
  package:
    name: open-vm-tools
    state: present
  when: ansible_virtualization_type == "VMware" and ansible_virtualization_role == "guest" 
