---
# tasks file for ansible-prep

# This file simply directs Ansible to run the right set of instructions depending on whether we're using Sudo or Su to gain privilaged access
# This file only exists to support Debian because they 'still' have a root account by default.

- name: Affect Default User - RHEL Family (sudo)
  include_tasks: user/sudo.yml
  when: ansible_os_family == "RedHat"


- name: Affect Default User - Ubuntu (sudo)
  include_tasks: user/sudo.yml
  when: ansible_distribution == "Ubuntu"


- name: Affect Default User - Raspbian (sudo)
  include_tasks: user/sudo.yml
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Raspbian"


- name: Affect Default User - Debian (su)
  include_tasks: user/su.yml
  when:
    - ansible_os_family == "Debian"
    - ansible_lsb.id == "Debian"
