---
# tasks file for base_httpd

- name: Add user 'tristan'
  user:
    name: tristan
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeCsal$oacN6onD8p6d/wmtIVwUh1
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present
    update_password: on_create


- name: Add authoirzed key for 'tristan'
  authorized_key:
    user: tristan
    state: present
    key: https://github.com/tfindley.keys


- name: Add user 'philote'
  user:
    name: philote
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$u7WbTX3IA3U5ugjt0GW.P1
    shell: /bin/bash
    groups: sudo,adm
    append: yes
    state: present
    update_password: on_create
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Add user 'philote'
  user:
    name: philote
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$u7WbTX3IA3U5ugjt0GW.P1
    shell: /bin/bash
    groups: wheel
    append: yes
    state: present
    update_password: on_create
  when: ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "CentOS"

- name: Add authorized key for 'philote'
  authorized_key:
    user: philote
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"


- name: Remove user 'pi'
  user:
    name: pi
    state: absent
    remove: yes
