---
# tasks file for ansible-prep

- name: Check if user {{ default_usr }} exists
  getent:
    database: passwd
    key: "{{ default_usr }}"
  register: user_chk
  ignore_errors: True

- name: Lock down or Delete {{ default_usr }} user
  block:

  - name: Lock down user {{ default_usr }} user (if it exists and is in use)
    user:
      name: "{{ default_usr }}"
      # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
      password: "{{ansible_pwd}}"
      shell: /dev/null
      groups: null
      append: no
      state: present
      update_password: always
#    when: ansible_user_id == default_usr
    when: user_chk is succeeded and user_lockdown == "True"
    register: user_locked


  - name: User is not {{ default_usr }}
    block: 
    - name: kill all processes owned by user {{ default_usr }}
      action: shell pkill -u {{ default_usr }}
      ignore_errors: True
    - name: Remove user {{ default_usr }} (when not in use)
      user:
          name: "{{ default_usr }}"
          state: absent
          remove: yes
      register: user_remove
    when: not ansible_user_id == default_usr

  when: user_chk is succeeded 
