---
# tasks file for ansible-prep
- name: Lock down user {{ default_usr }} user (if it exists and is in use)
  user:
    name: "{{ default_usr }}"
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: "{{ ansible_pwd }}"
    shell: /dev/null
    groups: null
    append: no
    state: present
    update_password: always
#    when: ansible_user_id == default_usr
  when:
    - default_usr in ansible_facts.getent_passwd
    - user_lockdown


- name: User is not {{ default_usr }}
  block:

  - name: kill all processes owned by user {{ default_usr }} # noqa 305
    action: shell pkill -u {{ default_usr }}
    ignore_errors: True
    when: default_usr_active.rc == 1

  - name: Remove user {{ default_usr }} (when not in use)
    user:
      name: "{{ default_usr }}"
      state: absent
      remove: yes

  when:
    - default_usr in ansible_facts.getent_passwd
    - ansible_usr in ansible_facts.getent_passwd
    - user_delete
    - default_usr is ansible_usr
