---
# tasks file for ansible-prep


- name: Lock down or Delete {{ default_usr }} user
  block:

  - name: Lock down user {{ default_usr }} (if it exists and is in use)
    user:
      name: "{{ default_usr }}"
      password: "{{ansible_pwd}}"
      shell: /dev/null
      groups: null
      append: no
      state: present
      update_password: always
    when: ansible_env.SUDO_USER == default_usr and user_lockdown == True


  - name: User or Sudo user is not {{ default_usr }}
    block: 

    - name: kill all processes owned by user {{ default_usr }}
      action: shell pkill -u {{ default_usr }}
      ignore_errors: True
      when: ansible_env.SUDO_USER != default_usr


    - name: Delete user {{ default_usr }}
      user:
          name: "{{ default_usr }}"
          state: absent
          remove: yes
    when: ansible_env.SUDO_USER != default_usr

  when: default_usr in ansible_facts.getent_passwd and ansible_usr in ansible_facts.getent_passwd and user_delete == True
