---
# tasks file for ansible-prep

- name: Install EPEL Release repo
  yum:
    name: epel-release


- name: Install SELinux Python Library
  yum:
    name: libselinux-python
  when: ansible_selinux_python_present == "false"


- name: Install a list of ansible-required packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - curl
    - tar
